- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start apache2 (Ubuntu)
  tags: apache,apache2,ubuntu
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: copy html file for site
  tags: apache,apache2,ubuntu
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
